using System.ComponentModel.DataAnnotations;

namespace VibeGuess.Core.Entities;

/// <summary>
/// Represents metadata about how a quiz was generated by AI.
/// </summary>
public class QuizGenerationMetadata : BaseEntity
{

    /// <summary>
    /// Foreign key to the Quiz entity.
    /// </summary>
    public Guid QuizId { get; set; }

    /// <summary>
    /// Time taken to process the generation request (milliseconds).
    /// </summary>
    public int ProcessingTimeMs { get; set; }

    /// <summary>
    /// AI model used for generation (e.g., "gpt-4", "gpt-3.5-turbo").
    /// </summary>
    [Required]
    [MaxLength(100)]
    public string AiModel { get; set; } = string.Empty;

    /// <summary>
    /// Version of the AI model used.
    /// </summary>
    [MaxLength(50)]
    public string? AiModelVersion { get; set; }

    /// <summary>
    /// Number of Spotify tracks found during generation.
    /// </summary>
    public int TracksFound { get; set; }

    /// <summary>
    /// Number of tracks that passed validation.
    /// </summary>
    public int TracksValidated { get; set; }

    /// <summary>
    /// Number of API tokens consumed during generation.
    /// </summary>
    public int TokensConsumed { get; set; }

    /// <summary>
    /// Estimated cost of the generation in cents.
    /// </summary>
    public decimal EstimatedCostCents { get; set; }

    /// <summary>
    /// Any warnings or issues encountered during generation.
    /// </summary>
    [MaxLength(2000)]
    public string? Warnings { get; set; }

    /// <summary>
    /// Raw AI prompt sent to the model (for debugging).
    /// </summary>
    [MaxLength(4000)]
    public string? RawPrompt { get; set; }

    /// <summary>
    /// Raw AI response received from the model (for debugging).
    /// </summary>
    public string? RawResponse { get; set; }

    /// <summary>
    /// When the generation was completed (alias for CreatedAt).
    /// </summary>
    public DateTime GeneratedAt => CreatedAt;

    // Navigation properties

    /// <summary>
    /// The quiz this metadata belongs to.
    /// </summary>
    public Quiz Quiz { get; set; } = null!;
}